version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  scraper-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3001
    depends_on:
      - redis
    volumes:
      - ./backend:/app/backend
      - ./src:/app/src

  api-server:
    build: .
    ports:
      - "3002:3002"
    environment:
      - API_PORT=3002
    volumes:
      - ./backend:/app/backend

volumes:
  redis_data: 